name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - name: 🙌 Build
        run: npm run electron:windows
      - name: Create Released Folder
        run: mkdir released
      - name: 🎉 Run Copy File Step
        run: node build/copy-file.js
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server01.codext.de
          username: codext_ftp_upload
          password: ${{ secrets.ftp_password }}
          local-dir: ./released/
          server-dir: windows10-tweaks/
      - name: 📂 GitHub Deploy
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: false
          files: |
            release/*.exe
